[tool.ruff]
target-version = "py311"
line-length = 88

src = ["custom_components"]

[tool.ruff.lint]
select = ["E", "F", "W"]
ignore = []

[tool.ruff.format]

[tool.ruff.lint.per-file-ignores]
"custom_components/energy_tracker/__init__.py" = ["F401"]

[tool.pytest.ini_options]
asyncio_mode = "auto"
filterwarnings = [
    "ignore::DeprecationWarning:homeassistant.components.http",
]

[tool.mypy]
python_version = "3.11"
ignore_missing_imports = true
follow_imports = "skip"
strict_optional = false
